// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package grpc_demo.news.proto;

public final class NewsProto {
  private NewsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NewsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.NewsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 date = 1;</code>
     * @return The date.
     */
    long getDate();
  }
  /**
   * Protobuf type {@code news.NewsRequest}
   */
  public static final class NewsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.NewsRequest)
      NewsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NewsRequest.newBuilder() to construct.
    private NewsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewsRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NewsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NewsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              date_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc_demo.news.proto.NewsProto.internal_static_news_NewsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc_demo.news.proto.NewsProto.internal_static_news_NewsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc_demo.news.proto.NewsProto.NewsRequest.class, grpc_demo.news.proto.NewsProto.NewsRequest.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    private long date_;
    /**
     * <code>int64 date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public long getDate() {
      return date_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (date_ != 0L) {
        output.writeInt64(1, date_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (date_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, date_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc_demo.news.proto.NewsProto.NewsRequest)) {
        return super.equals(obj);
      }
      grpc_demo.news.proto.NewsProto.NewsRequest other = (grpc_demo.news.proto.NewsProto.NewsRequest) obj;

      if (getDate()
          != other.getDate()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.NewsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc_demo.news.proto.NewsProto.NewsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code news.NewsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.NewsRequest)
        grpc_demo.news.proto.NewsProto.NewsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_NewsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_NewsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc_demo.news.proto.NewsProto.NewsRequest.class, grpc_demo.news.proto.NewsProto.NewsRequest.Builder.class);
      }

      // Construct using grpc_demo.news.proto.NewsProto.NewsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        date_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_NewsRequest_descriptor;
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.NewsRequest getDefaultInstanceForType() {
        return grpc_demo.news.proto.NewsProto.NewsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.NewsRequest build() {
        grpc_demo.news.proto.NewsProto.NewsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.NewsRequest buildPartial() {
        grpc_demo.news.proto.NewsProto.NewsRequest result = new grpc_demo.news.proto.NewsProto.NewsRequest(this);
        result.date_ = date_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc_demo.news.proto.NewsProto.NewsRequest) {
          return mergeFrom((grpc_demo.news.proto.NewsProto.NewsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc_demo.news.proto.NewsProto.NewsRequest other) {
        if (other == grpc_demo.news.proto.NewsProto.NewsRequest.getDefaultInstance()) return this;
        if (other.getDate() != 0L) {
          setDate(other.getDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc_demo.news.proto.NewsProto.NewsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc_demo.news.proto.NewsProto.NewsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long date_ ;
      /**
       * <code>int64 date = 1;</code>
       * @return The date.
       */
      @java.lang.Override
      public long getDate() {
        return date_;
      }
      /**
       * <code>int64 date = 1;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(long value) {
        
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 date = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:news.NewsRequest)
    }

    // @@protoc_insertion_point(class_scope:news.NewsRequest)
    private static final grpc_demo.news.proto.NewsProto.NewsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc_demo.news.proto.NewsProto.NewsRequest();
    }

    public static grpc_demo.news.proto.NewsProto.NewsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewsRequest>
        PARSER = new com.google.protobuf.AbstractParser<NewsRequest>() {
      @java.lang.Override
      public NewsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc_demo.news.proto.NewsProto.NewsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NewsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.NewsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    java.util.List<grpc_demo.news.proto.NewsProto.News> 
        getNewsList();
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    grpc_demo.news.proto.NewsProto.News getNews(int index);
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    int getNewsCount();
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    java.util.List<? extends grpc_demo.news.proto.NewsProto.NewsOrBuilder> 
        getNewsOrBuilderList();
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    grpc_demo.news.proto.NewsProto.NewsOrBuilder getNewsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code news.NewsResponse}
   */
  public static final class NewsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.NewsResponse)
      NewsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NewsResponse.newBuilder() to construct.
    private NewsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewsResponse() {
      news_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NewsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NewsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                news_ = new java.util.ArrayList<grpc_demo.news.proto.NewsProto.News>();
                mutable_bitField0_ |= 0x00000001;
              }
              news_.add(
                  input.readMessage(grpc_demo.news.proto.NewsProto.News.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          news_ = java.util.Collections.unmodifiableList(news_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc_demo.news.proto.NewsProto.internal_static_news_NewsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc_demo.news.proto.NewsProto.internal_static_news_NewsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc_demo.news.proto.NewsProto.NewsResponse.class, grpc_demo.news.proto.NewsProto.NewsResponse.Builder.class);
    }

    public static final int NEWS_FIELD_NUMBER = 1;
    private java.util.List<grpc_demo.news.proto.NewsProto.News> news_;
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    @java.lang.Override
    public java.util.List<grpc_demo.news.proto.NewsProto.News> getNewsList() {
      return news_;
    }
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends grpc_demo.news.proto.NewsProto.NewsOrBuilder> 
        getNewsOrBuilderList() {
      return news_;
    }
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    @java.lang.Override
    public int getNewsCount() {
      return news_.size();
    }
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    @java.lang.Override
    public grpc_demo.news.proto.NewsProto.News getNews(int index) {
      return news_.get(index);
    }
    /**
     * <pre>
     *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    @java.lang.Override
    public grpc_demo.news.proto.NewsProto.NewsOrBuilder getNewsOrBuilder(
        int index) {
      return news_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < news_.size(); i++) {
        output.writeMessage(1, news_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < news_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, news_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc_demo.news.proto.NewsProto.NewsResponse)) {
        return super.equals(obj);
      }
      grpc_demo.news.proto.NewsProto.NewsResponse other = (grpc_demo.news.proto.NewsProto.NewsResponse) obj;

      if (!getNewsList()
          .equals(other.getNewsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNewsCount() > 0) {
        hash = (37 * hash) + NEWS_FIELD_NUMBER;
        hash = (53 * hash) + getNewsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.NewsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc_demo.news.proto.NewsProto.NewsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code news.NewsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.NewsResponse)
        grpc_demo.news.proto.NewsProto.NewsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_NewsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_NewsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc_demo.news.proto.NewsProto.NewsResponse.class, grpc_demo.news.proto.NewsProto.NewsResponse.Builder.class);
      }

      // Construct using grpc_demo.news.proto.NewsProto.NewsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNewsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_NewsResponse_descriptor;
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.NewsResponse getDefaultInstanceForType() {
        return grpc_demo.news.proto.NewsProto.NewsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.NewsResponse build() {
        grpc_demo.news.proto.NewsProto.NewsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.NewsResponse buildPartial() {
        grpc_demo.news.proto.NewsProto.NewsResponse result = new grpc_demo.news.proto.NewsProto.NewsResponse(this);
        int from_bitField0_ = bitField0_;
        if (newsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            news_ = java.util.Collections.unmodifiableList(news_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.news_ = news_;
        } else {
          result.news_ = newsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc_demo.news.proto.NewsProto.NewsResponse) {
          return mergeFrom((grpc_demo.news.proto.NewsProto.NewsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc_demo.news.proto.NewsProto.NewsResponse other) {
        if (other == grpc_demo.news.proto.NewsProto.NewsResponse.getDefaultInstance()) return this;
        if (newsBuilder_ == null) {
          if (!other.news_.isEmpty()) {
            if (news_.isEmpty()) {
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsIsMutable();
              news_.addAll(other.news_);
            }
            onChanged();
          }
        } else {
          if (!other.news_.isEmpty()) {
            if (newsBuilder_.isEmpty()) {
              newsBuilder_.dispose();
              newsBuilder_ = null;
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNewsFieldBuilder() : null;
            } else {
              newsBuilder_.addAllMessages(other.news_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc_demo.news.proto.NewsProto.NewsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc_demo.news.proto.NewsProto.NewsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<grpc_demo.news.proto.NewsProto.News> news_ =
        java.util.Collections.emptyList();
      private void ensureNewsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          news_ = new java.util.ArrayList<grpc_demo.news.proto.NewsProto.News>(news_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc_demo.news.proto.NewsProto.News, grpc_demo.news.proto.NewsProto.News.Builder, grpc_demo.news.proto.NewsProto.NewsOrBuilder> newsBuilder_;

      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public java.util.List<grpc_demo.news.proto.NewsProto.News> getNewsList() {
        if (newsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(news_);
        } else {
          return newsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public int getNewsCount() {
        if (newsBuilder_ == null) {
          return news_.size();
        } else {
          return newsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public grpc_demo.news.proto.NewsProto.News getNews(int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);
        } else {
          return newsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder setNews(
          int index, grpc_demo.news.proto.NewsProto.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.set(index, value);
          onChanged();
        } else {
          newsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder setNews(
          int index, grpc_demo.news.proto.NewsProto.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(grpc_demo.news.proto.NewsProto.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(value);
          onChanged();
        } else {
          newsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(
          int index, grpc_demo.news.proto.NewsProto.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(index, value);
          onChanged();
        } else {
          newsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(
          grpc_demo.news.proto.NewsProto.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(
          int index, grpc_demo.news.proto.NewsProto.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addAllNews(
          java.lang.Iterable<? extends grpc_demo.news.proto.NewsProto.News> values) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, news_);
          onChanged();
        } else {
          newsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder clearNews() {
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder removeNews(int index) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.remove(index);
          onChanged();
        } else {
          newsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public grpc_demo.news.proto.NewsProto.News.Builder getNewsBuilder(
          int index) {
        return getNewsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public grpc_demo.news.proto.NewsProto.NewsOrBuilder getNewsOrBuilder(
          int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);  } else {
          return newsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public java.util.List<? extends grpc_demo.news.proto.NewsProto.NewsOrBuilder> 
           getNewsOrBuilderList() {
        if (newsBuilder_ != null) {
          return newsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(news_);
        }
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public grpc_demo.news.proto.NewsProto.News.Builder addNewsBuilder() {
        return getNewsFieldBuilder().addBuilder(
            grpc_demo.news.proto.NewsProto.News.getDefaultInstance());
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public grpc_demo.news.proto.NewsProto.News.Builder addNewsBuilder(
          int index) {
        return getNewsFieldBuilder().addBuilder(
            index, grpc_demo.news.proto.NewsProto.News.getDefaultInstance());
      }
      /**
       * <pre>
       *repeated说明是一个对象集合  不同语言生成的集合类型不同 例如Java生成List，javascript生成数组。。。等等
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public java.util.List<grpc_demo.news.proto.NewsProto.News.Builder> 
           getNewsBuilderList() {
        return getNewsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc_demo.news.proto.NewsProto.News, grpc_demo.news.proto.NewsProto.News.Builder, grpc_demo.news.proto.NewsProto.NewsOrBuilder> 
          getNewsFieldBuilder() {
        if (newsBuilder_ == null) {
          newsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              grpc_demo.news.proto.NewsProto.News, grpc_demo.news.proto.NewsProto.News.Builder, grpc_demo.news.proto.NewsProto.NewsOrBuilder>(
                  news_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          news_ = null;
        }
        return newsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:news.NewsResponse)
    }

    // @@protoc_insertion_point(class_scope:news.NewsResponse)
    private static final grpc_demo.news.proto.NewsProto.NewsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc_demo.news.proto.NewsProto.NewsResponse();
    }

    public static grpc_demo.news.proto.NewsProto.NewsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewsResponse>
        PARSER = new com.google.protobuf.AbstractParser<NewsResponse>() {
      @java.lang.Override
      public NewsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc_demo.news.proto.NewsProto.NewsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NewsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.News)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code news.News}
   */
  public static final class News extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.News)
      NewsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use News.newBuilder() to construct.
    private News(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private News() {
      title_ = "";
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new News();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private News(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc_demo.news.proto.NewsProto.internal_static_news_News_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc_demo.news.proto.NewsProto.internal_static_news_News_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc_demo.news.proto.NewsProto.News.class, grpc_demo.news.proto.NewsProto.News.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc_demo.news.proto.NewsProto.News)) {
        return super.equals(obj);
      }
      grpc_demo.news.proto.NewsProto.News other = (grpc_demo.news.proto.NewsProto.News) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.News parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.News parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo.news.proto.NewsProto.News parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc_demo.news.proto.NewsProto.News prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code news.News}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.News)
        grpc_demo.news.proto.NewsProto.NewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_News_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_News_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc_demo.news.proto.NewsProto.News.class, grpc_demo.news.proto.NewsProto.News.Builder.class);
      }

      // Construct using grpc_demo.news.proto.NewsProto.News.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        content_ = "";

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc_demo.news.proto.NewsProto.internal_static_news_News_descriptor;
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.News getDefaultInstanceForType() {
        return grpc_demo.news.proto.NewsProto.News.getDefaultInstance();
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.News build() {
        grpc_demo.news.proto.NewsProto.News result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc_demo.news.proto.NewsProto.News buildPartial() {
        grpc_demo.news.proto.NewsProto.News result = new grpc_demo.news.proto.NewsProto.News(this);
        result.id_ = id_;
        result.title_ = title_;
        result.content_ = content_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc_demo.news.proto.NewsProto.News) {
          return mergeFrom((grpc_demo.news.proto.NewsProto.News)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc_demo.news.proto.NewsProto.News other) {
        if (other == grpc_demo.news.proto.NewsProto.News.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc_demo.news.proto.NewsProto.News parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc_demo.news.proto.NewsProto.News) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:news.News)
    }

    // @@protoc_insertion_point(class_scope:news.News)
    private static final grpc_demo.news.proto.NewsProto.News DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc_demo.news.proto.NewsProto.News();
    }

    public static grpc_demo.news.proto.NewsProto.News getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<News>
        PARSER = new com.google.protobuf.AbstractParser<News>() {
      @java.lang.Override
      public News parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new News(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<News> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<News> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc_demo.news.proto.NewsProto.News getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_News_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_News_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnews.proto\022\004news\"\033\n\013NewsRequest\022\014\n\004dat" +
      "e\030\001 \001(\003\"(\n\014NewsResponse\022\030\n\004news\030\001 \003(\0132\n." +
      "news.News\"E\n\004News\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002" +
      " \001(\t\022\017\n\007content\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003" +
      "2>\n\013NewsService\022/\n\004list\022\021.news.NewsReque" +
      "st\032\022.news.NewsResponse\"\000B#\n\024grpc_demo.ne" +
      "ws.protoB\tNewsProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_news_NewsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_news_NewsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsRequest_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_news_NewsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_news_NewsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsResponse_descriptor,
        new java.lang.String[] { "News", });
    internal_static_news_News_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_news_News_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_News_descriptor,
        new java.lang.String[] { "Id", "Title", "Content", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
